### ISSUE TITLE
Unable to redirect the output in a file in tracemode

### ISSUE THREAD

**Issue by thedwarf21** [raboof/nethogs#107]
I launched this command:
`sudo nethogs -t | awk '$1 ~ /'"\/[my_process_pid]\/"'/ { print $2":"$3 >> "[my_process_pid]" }'`

Nothing appears on my screen but the output file stays empty which is not my purpose. Therefore when I just launch:
`sudo nethogs -t | awk '$1 ~ /'"\/[my_process_pid]\/"'/ { print $2":"$3 }' `

Without trying to redirect the output, I get a consistent result on my screen.
I would like to be able to redirect the output of the command into a file in order to use the result in my program.

Edit : After I let the command run a few minutes, my output file gets some values ...

**Comment by thedwarf21** [comment]
An option providing file redirection would be sufficient, by the way

**Comment by raboof** [comment]
Are you sure your awk filter is OK? `nethogs -t > out.txt` seems to work fine here. Can you check `cat out.txt | your-awk-script` works?

**Comment by thedwarf21** [comment]
Hello,

Actually, checking my awk script was working, was the first thing I tried,
and it works fine if I don't try to redirect the stream to a file. However,
I found a way to make the hole script work, adding a system function
invocation into my awk script, which forces awk to flush his buffer.

This shows that nethogs was not in cause but only awk.

Thank you.

2016-12-30 17:56 GMT+01:00 Arnout Engelen <notifications@github.com>:

**Comment by raboof** [comment]
Great good to hear you got it to work!

**Comment by QiangF** [comment]
> However, I found a way to make the hole script work, adding a system function invocation into my awk script, which forces awk to flush his buffer. 

Can you share your solution here?
People suggests to use a temp file in the other issue
https://github.com/raboof/nethogs/issues/38
