### ISSUE TITLE
how to run nethogs in java? thanks

### ISSUE THREAD

**Issue by sknny7** [raboof/nethogs#115]
java code:
		ShellCommandExecutor shellExecutor = new ShellCommandExecutor(
				  new String[] { "sudo", "/bin/sh", "-c", "nethogs"
						  });
               shellExecutor.execute();

cause: ExitCodeException exitCode=1: Error opening terminal: unknown.

**Comment by sknny7** [comment]
i had sloved that problem, but the output contains messy words.

are there some approach to disable the dynamic refresh of nethogs?

**Comment by raboof** [comment]
I'm not sure what you'd want to achieve, but the default 'curses' interface is meant for 'interactive' consumption.

If you'd like to get something more easily machine-readable, you might want to consider the 'trace mode' enabled with the '-t' flag.

If you don't want to automatically refresh you may specify a 'count' with '-c' defining how many iterations to run.

**Comment by sknny7** [comment]
Thanks very much, "trace mode" is what i want.

**Comment by raboof** [comment]
Great!
