### ISSUE TITLE
pcap expression support / ssh exclusion?

### ISSUE THREAD

**Issue by rmenessec** [raboof/nethogs#119]
When trying to use nethogs remotely, I'm finding that there doesn't appear to be any way to exclude my own ssh traffic--or any other traffic that I'd like to filter out for whatever reason. I'm not seeing any documentation indicating that this can be done either from the command line or from the interactive interface.

Could you add pcap expression support, to help filter out traffic that I don't want analyzed? Without this functionality, I'm finding that it's easier to use [iftop](http://www.ex-parrot.com/pdw/iftop/), then go associate a session with a process.

Thanks!

**Comment by raboof** [comment]
Would be a nice feature, and since we're using libpcap to monitor the network traffic anyway, might not even be that hard to realize.

Currently not high on my own priority list, but PR's certainly welcome!

**Comment by rmenessec** [comment]
In the meantime, do you know of any way to attach a filter to an existing process?

Or is there some other way I could perform the filtering in front of nethogs, before it measures traffic?

**Comment by jantman** [comment]
I don't have the development experience to implement this, but I was just looking through issues and came by it. It _should_ be pretty easy to implement, as libpcap has built-in support for filter expressions.
