### ISSUE TITLE
Fix sf.net site to point to github

### ISSUE THREAD

**Issue by afsilva** [raboof/nethogs#12]
I maintain nethogs in Fedora and EPEL and looking at the "official" site http://nethogs.sourceforge.net/, I don't see it is obvious that nethogs has moved to github. I thought the program hadn't been updated in a few years to be honest.

Is is safe to assume that this is the new canical source? And if yes, is 0.8.2 the latest stable version?

I intend to update the package in Fedora soon.

Thank you.

**Comment by raboof** [comment]
Thanks for taking an interest in nethogs! Yes, 0.8.2 is the latest stable version and we should probably make this the canonical source for nethogs.

**Comment by raboof** [comment]
I think I've moved most interesting resources over - feel free to re-open this issue if you seen anything further!
