### ISSUE TITLE
Interpretation of the output address:port-address:port

### ISSUE THREAD

**Issue by borir** [raboof/nethogs#125]
Sometimes nothogs reports address_of_my_machine:port-another_address:port instead of the name of the program and the process id is displayed as '?'. What does this mean? I couldn't find anything about this from the man page or the readme.

**Comment by raboof** [comment]
This is what nethogs falls back to when it cannot find any process to associate with this connection. Would you like to contribute a note for the man page or readme?

**Comment by borir** [comment]
I was just curious about that :) I don't think that it must be explained in the man page or readme.
Anyway I'm interested in the possible cases in which nethogs cannot determine the process. I'll be happy if you show some typical cases.

**Comment by raboof** [comment]
The most typical case is when an application creates many connections that only exist for a short amount of time. I'm not sure, but I think bittorrent is an example of that. 

The way nethogs works is by scanning `/proc/net/tcp` and using libpcap to get information about connections (including inodes), and scanning `/proc/<pid>/fd/*` to get information about processes (including inodes). That information is associated by, you guessed it, inode. If we're unlucky, however, we might see a connection but will be too late to also see the corresponding inode in `/proc/<pid>/fd/*`. In that case we won't be able to make a match.

Another option is that there might be some NAT stuff going on making it hard to match things up, but I suspect that's rarer.

Does that help?

**Comment by borir** [comment]
Thank you for the reply, and nethogs. It helped me a lot.
