### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by joelaldor** [raboof/nethogs#126]
When I do make:

```
ubuntu@PHMARCHES3DEV:~/nethogs$ sudo make
make -C src -f MakeApp.mk decpcap_test
make[1]: Entering directory `/home/ubuntu/nethogs/src'
cc  -Wall -Wextra -c decpcap.c
decpcap.c:31:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
make[1]: *** [decpcap.o] Error 1
make[1]: Leaving directory `/home/ubuntu/nethogs/src'
make: *** [decpcap_test] Error 2
```

Kindly check what is causing this.

**Comment by wioxjk** [comment]
I have the same error

**Comment by wioxjk** [comment]
I am stupid, just install "build-essential" and you can proceed

**Comment by raboof** [comment]
@joelaldor did you see https://github.com/raboof/nethogs#building-from-source ? `pcap.h` should come with `libpcap-dev` (on deb-based systems) or `libpcap.x86_64` (on yum-based systems). Does that help?

**Comment by ravi45722** [comment]
I installed everything and compiled. Its created a binary named `nethogs`. But I am looking for `libnethogs.so.0.8.5` which I cannot find anywhere. I checked all `/usr/lib, /usr/lib64, /usr/local/lib, /usr/local/lib64`. But no luck. I want to use the python version. So I need this library. Where can I find it???

**Comment by ravi45722** [comment]
Finally I find a alternative. For reference to those searching to install offline
`https://slackware.pkgs.org/14.2/slackonly-x86_64/nethogs-0.8.5-x86_64-2_slonly.txz.html`

**Comment by raboof** [comment]
@ravi45722 that does not have anything to do with this issue, it would have been better to open a new one.

Did you see the [libnethogs section of the README](https://github.com/raboof/nethogs#libnethogs)?
