### ISSUE TITLE
Assertion m_pid <= 100000

### ISSUE THREAD

**Issue by manfredsc** [raboof/nethogs#14]
just got the following:

root# nethogs ext0
Ethernet link detected
                      Waiting for first packet to arrive (see sourceforge.net bug 1019381)
?     root     unknown TCP                                                                                                 0.000       0.000 KB/sec

  TOTAL                                                                                                                   13.435     220.736 KB/sec
Couldn't open dir /proc/329478/fd: No such file or directory
                                                            Couldn't open dir /proc/329483/fd: No such file or directory
                                                                                                                        Couldn't open dir /proc/329488/fd: No such file or directory
                                Couldn't open dir /proc/329491/fd: No such file or directory
                                                                                            Couldn't open dir /proc/329492/fd: No such file or directory
    Couldn't open dir /proc/329525/fd: No such file or directory
                                                                Couldn't open dir /proc/329532/fd: No such file or directory
                                                                                                                            Couldn't open dir /proc/329535/fd: No such file or directory
                                    Couldn't open dir /proc/329541/fd: No such file or directory
                                                                                                Couldn't open dir /proc/329562/fd: No such file or directory
        Couldn't open dir /proc/329563/fd: No such file or directory
                                                                    Couldn't open dir /proc/329564/fd: No such file or directory
                                                                                                                                Couldn't open dir /proc/329731/fd: No such file or directory
                                        Couldn't open dir /proc/329732/fd: No such file or directory
                                                                                                    Couldn't open dir /proc/329733/fd: No such file or directory
            Couldn't open dir /proc/329737/fd: No such file or directory
                                                                        Couldn't open dir /proc/329738/fd: No such file or directory
                                                                                                                                    Couldn't open dir /proc/329759/fd: No such file or directory
                                            Couldn't open dir /proc/329692/fd: No such file or directory
                                                                                                        Couldn't open dir /proc/329693/fd: No such file or directory
                Couldn't open dir /proc/329694/fd: No such file or directory
                                                                            Couldn't open dir /proc/329821/fd: No such file or directory
                                                                                                                                        Couldn't open dir /proc/329822/fd: No such file or directory
                                                Couldn't open dir /proc/329830/fd: No such file or directory
                                                                                                            Couldn't open dir /proc/329832/fd: No such file or directory
                    Couldn't open dir /proc/329845/fd: No such file or directory
                                                                                Couldn't open dir /proc/329846/fd: No such file or directory
                                                                                                                                            Couldn't open dir /proc/329934/fd: No such file or directory
                                                    Couldn't open dir /proc/329961/fd: No such file or directory
                                                                                                                Couldn't open dir /proc/330087/fd: No such file or directory
                        Couldn't open dir /proc/330088/fd: No such file or directory
                                                                                    Couldn't open dir /proc/330176/fd: No such file or directory
                                                                                                                                                Couldn't open dir /proc/330247/fd: No such file or directory
                                                        Couldn't open dir /proc/330249/fd: No such file or directory
                                                                                                                    Couldn't open dir /proc/330251/fd: No such file or directory
                            Couldn't open dir /proc/330260/fd: No such file or directory
                                                                                        Couldn't open dir /proc/330270/fd: No such file or directory
                                                                                                                                                   Couldn't open dir /proc/330348/fd: No such file or directory
                                                           nethogs: cui.cpp:80: void Line::show(int, unsigned int): Assertion `m_pid <= 100000' failed.
   Aborted

Number of PID's is freely configurable. On my box:
root# cat /proc/sys/kernel/pid_max
514055

**Comment by raboof** [comment]
Thanks, that restriction indeed makes no sense, it should be dropped.

**Comment by manfredsc** [comment]
Thanks for looking into this.
BTW: Is there a way to suppress all these "couldn't open dir..." messages?
They annoy very much. Really.
Besides this, great tool, thanks!

**Comment by raboof** [comment]
Thanks!

Yes I could probably do something against those 'couldn't open dir' messages, for example only log them in debug mode. Can you make a separate issue for that?

**Comment by raboof** [comment]
Actually, this assertion has been upped to PID_MAX=4194303 in a0fefea9 - so a more recent version of nethogs should no longer have this problem.

**Comment by raboof** [comment]
(actually even before that commit it looks like, but I don't feel like archaeology today :)
