### ISSUE TITLE
Error handling of reading /proc/<pid>/ need improvement

### ISSUE THREAD

**Issue by duanyao** [raboof/nethogs#145]
A process may exit at *any* time when nethogs is walking through `/proc/<pid>`, so the IO errors should be handled properly. E.g., calling `read_file()` on `/proc/<pid>/cmdline`:

https://github.com/raboof/nethogs/blob/7093964413c086f7eee06cbe257f2a579caae209/src/inode2prog.cpp#L98-L106

If the process exits after L98 but before L99, you get a `ENOENT`. This is not a fatal error and nethogs should not exit.

https://github.com/raboof/nethogs/blob/7093964413c086f7eee06cbe257f2a579caae209/src/inode2prog.cpp#L83-L91

If the process exits after L83 but before L87, you get a `ESRCH`. Again this is not a fatal error and nethogs should not exit.

Actually, I don't think nethogs should exit at any IO errors in `/proc/`, just ignore and retry later.

**Comment by raboof** [comment]
You are, of course, completely right! Would you be interested in preparing a PR?

**Comment by duanyao** [comment]
I'm interested but I'm new to nethogs's code base, so it may take some time to get familiar with it.

**Comment by raboof** [comment]
No problem, let me know if you have any questions!

**Comment by raboof** [comment]
reportedly fixed by #175
