### ISSUE TITLE
Eat 100% CPU if monitor too many processes.

### ISSUE THREAD

**Issue by Sraw** [raboof/nethogs#166]
I've left nethogs running over night and find it use 100% CPU.
Here is an image about cpu usage:
![image](https://user-images.githubusercontent.com/15711730/42980961-45190894-8c0c-11e8-93ee-1624b1e72b46.png)

It grows from nearly 0 to 100% in two hours.

I'm using the following command: `nethogs -v 1 eth0`.

I'm not surely where is the point. But I guess it is because that `nethogs` was monitoring too many processes. Almost every ten seconds, my computer will create a process and launch a connection to send some information, then terminate that process. That leaves a record in `nethogs` although it won't be updated in the future.

So during the night, there will be hundreds or even thansands of records in `nethogs`. Will it cause problems? If it will, should we have an option to filter process's name or something else?

**Comment by NeilZhy** [comment]
Has this issue been resolved?

**Comment by raboof** [comment]
#223 might have helped here
