### ISSUE TITLE
Nethogs cmdline still  SegmentFault crash 2-10h apart

### ISSUE THREAD

**Issue by gunnar12** [raboof/nethogs#169]
Running in gdb, without debug symbols,gdb gives 

Program received signal SIGSEGV, Segmentation fault.
0x000000000040b2ee in getcmdline[abi:cxx11](int) ()

My 5-second hope on just increasing string length in getcmdline was of course just BS after I figured out the code and how,where the cmdline string comes from, full of 0x00s between the arguments.

Would be easy to find and debug better with my own debug compilation but dont know how to and where to change the Makefiles. Did some simpler ones 10 yrs ago $CFLAGS= -g but where and how?

Who, what frees the old cmdline strings, they are allocated by the read_file call, yes?

Wld be much easier wth actual debug code as I slowly remember gdb usage from ages ago.

Gunnar

**Comment by raboof** [comment]
> $CFLAGS= -g but where and how

Does `CXXFLAGS=-g make` work?

**Comment by gunnar12** [comment]
THANKS!!

gdb did "reading symbols, done!"

Now just wait while hating them std::strings..

**Comment by gunnar12** [comment]
random cmdline crash/

been busy, but seems the problemis that the cmdline is read from HD in many places, different times, and also treated, processed, allocated and freed? differently. THe linked process, socket list and final display on screen, etc

Still need time to remember all the gdb commands and features not to mix with other debuggers.

**Comment by raboof** [comment]
possibly fixed by #175, please reopen if it occurs after that
