### ISSUE TITLE
Remove Exit calls in error handling

### ISSUE THREAD

**Issue by azak-azkaran** [raboof/nethogs#176]
I have nethogs running non-stop in a tmux pane but sometimes it stops with errors while reading the cmdline files.

I would like to propose a change, to remove the exit while reading the cmdline file and just inform the user about the error. Since the cmdline files are removed if the process in question is short-lived or is removed while iterating over all proc folders.

**Comment by raboof** [comment]
I think some changes have been made in this area on master - have you tried that?

**Comment by azak-azkaran** [comment]
I have the newest version from the master.
But in [inode2prog.ccp](https://github.com/raboof/nethogs/blob/master/src/inode2prog.cpp) there is still some error handling which exits the program completely

https://github.com/raboof/nethogs/blob/a46b3d6f97337b12ac5818bc03135b7d1f246ec8/src/inode2prog.cpp#L87-L93

https://github.com/raboof/nethogs/blob/a46b3d6f97337b12ac5818bc03135b7d1f246ec8/src/inode2prog.cpp#L101-L106

https://github.com/raboof/nethogs/blob/a46b3d6f97337b12ac5818bc03135b7d1f246ec8/src/inode2prog.cpp#L110-L117

**Comment by raboof** [comment]
Sounds good, would you be interested in sending a PR?a

**Comment by azak-azkaran** [comment]
will do :)
