### ISSUE TITLE
nethogs -t | awk {'print $0}' return no output

### ISSUE THREAD

**Issue by nixinator** [raboof/nethogs#190]
nethogs is a linux process bandwidth monitoring tool. https://github.com/raboof/nethogs

`nethogs -t `

it's output looks like this.

```
    Refreshing:
    sshd: root@pts/0/4002/0 0.185156        0.0773437
    unknown TCP/0/0 0       0
    
    Refreshing:
    sshd: root@pts/0/4002/0 0.220703        0.0902344
    unknown TCP/0/0 0       0
    
    Refreshing:
    sshd: root@pts/0/4002/0 0.217578        0.0902344
    unknown TCP/0/0 0       0

```

I'm trying to to parse it's outout with awk.
`
    nethogs -t | awk '{print $0}' `

returns no output :-(

`    nethogs -t | awk '{readline tmp; print tmp}' `

much the same ;

I presume it's the way nethogs is buffering it's output or some other quirky way it's writing it's output. 

 `   nethogs -t | awk -W interactive '{print $2}'`

i get some output, but it's not working as expected.

I've tried playing with awk's RS and FS settings, but no luck.

Is this something to do with how nethogs is buffering it's output? do i need flush awk some way?

p.s nethogs is a great tool!

**Comment by raboof** [comment]
> returns no output :-(

Hmm, I can't reproduce that... what distro and shell are you using?

**Comment by nixinator** [comment]
Maybe it's some docker related nonsense.. or a really old version of Ubuntu.


$ cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

$ bash -version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

I'll try with an updated image and see what happens. Thanks for your help.

**Comment by Gtorjmene** [comment]
hello what's the solution for the problem i want to extract nethogs output in json file ! but failed

**Comment by Gtorjmene** [comment]
hello what's the solution for the problem i want to extract nethogs output in json file ! but failed

**Comment by wangjingwei0119** [comment]
Me too. I want to use the nethogs tool to obtain results and format the output, but it's either stuck or empty data, which has been bothering me for a long time. What did you finally do

**Comment by raboof** [comment]
> I presume it's the way nethogs is buffering it's output or some other quirky way it's writing it's output.

It's just printf... would be interesting to find out what was going on here ;)

> `nethogs -t | awk -W interactive '{print $2}'` actually works fine. So i put this down to old version of ubuntu, bash, awk or nethogs! :-).

Still strange the '-W interactive' isn't needed for me

> i want to extract nethogs output in json file ! but failed

See #64

**Comment by nixinator** [comment]
Oh hello @raboof, long time... good to see at Fosdem... 

Hope you well in a crazy world.

is this in nix now?

**Comment by raboof** [comment]
> Oh hello @raboof, long time... good to see at Fosdem...
>
> Hope you well in a crazy world.

You as well!
 
> is this in nix now?

Has been since 2014 it seems? https://github.com/NixOS/nixpkgs/commits/master/pkgs/tools/networking/nethogs/default.nix
