### ISSUE TITLE
The results of command "nethogs -d 1" is totally wrong

### ISSUE THREAD

**Issue by tlexy** [raboof/nethogs#191]
When I typed "nethogs -d 1", I got the totally wrong results. The correct results I could get from the "sar -n DEV 1". The actual traffic is about 200kB/s， but the nethogs only show 10kB/s。

**Comment by tlexy** [comment]
This tool only use to detect TCP traffic?

> When I typed "nethogs -d 1", I got the totally wrong results. The correct results I could get from the "sar -n DEV 1". The actual traffic is about 200kB/s， but the nethogs only show 10kB/s。

This tool only use to detect TCP traffic?

**Comment by raboof** [comment]
> This tool only use to detect TCP traffic?

That is correct! #62 tracks adding UDP support. Our old homepage made this clearer (https://web.archive.org/web/20080820101827/http://nethogs.sf.net/) but it looks like this didn't make it to the README. If you'd like to PR a clarification that'd be most welcome!
