### ISSUE TITLE
Counter resets after reaching 4.2 GB

### ISSUE THREAD

**Issue by orwa-te** [raboof/nethogs#195]
I am using `nethogs ` to monitor a process that may receive/transmit 300 GB of data through the network but after sometime the bytes counter automatically is reset to 0.
I have read in issue #29 that `nethogs` uses uint32 bit to store the number of bytes passing through the network, is there a way to increase the capacity of the counters in order to solve my problem?

**Comment by raboof** [comment]
This should already have been upped to uint64 since #137 - what version of nethogs are you on? Can you try updating to the latest master?

**Comment by orwa-te** [comment]
I use NetHogs version 0.8.5-2build2 which was installed on my Ubuntu20 using the command `sudo apt install nethogs`.
Do I understand right? Using the command `nethogs -v 3` may solve the problem!

**Comment by raboof** [comment]
> 0.8.5-2build2

#137 has been fixed between 0.8.5 and 0.8.6, so unless ubuntu has pulled in that patch separately I think the solution would be to upgrade.
