### ISSUE TITLE
nethogs significantly underestimating Zoom traffic

### ISSUE THREAD

**Issue by onavsaber** [raboof/nethogs#197]
I am using nethogs on Ubuntu 20.04. I have also zoom installed. During a meeting sharing video, tools like iftop show traffic to be in the orders of 200KB/s. However, nethogs shows zoom traffic at much lower speeds, like a few KB/s. I have build the latest version of nethogs from the repository.

**Comment by akash-258** [comment]
The same problem with google meet in the browser, show 1 KB/s where the actual speed is 50-100 KB/s

**Comment by raboof** [comment]
Are you sure you are looking at only TCP data? Nethogs doesn't count UDP data.

**Comment by onavsaber** [comment]
@raboof you are right. Thanks. When I include -C option, I do see reasonable traffic under "unknown UDP". 
Just curious, would Nethogs be able to monitor UDP in the future?

**Comment by raboof** [comment]
I'm not sure we can get really reliably data for those, see #62

I'll close this for now, if you see nethogs significantly underestimating TCP traffic feel free to re-open (or open a new issue)
