### ISSUE TITLE
BusyTasks is back

### ISSUE THREAD

**Issue by unknown-spirit** [raboof/nethogs#211]
Hi, 
You used to have BusyTasks on your link list [ BusyTasks link is dead #95 ](https://github.com/raboof/nethogs/issues/95)
Although it's been already several years that I rewrote the application using Java [BusyTasks on pling.com](https://www.pling.com/p/1201835), it sadly seems to be completely unknown to the majority of UNIX users. BusyTasks uses common UNIX command line tools like top, iotop and nethogs as backend. I wondered if you would be so nice to add it again to your list?
Thank you anyway

**Comment by raboof** [comment]
Thanks!
