### ISSUE TITLE
The capability check is too restrictive

### ISSUE THREAD

**Issue by ncfavier** [raboof/nethogs#214]
The NixOS security module uses [wrapper programs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/security/wrappers/default.nix) to set capabilities on executables. This fails with nethogs because it checks the capabilities of `/proc/self/exe` directly, which at the time of execution points to the wrapped program instead of the wrapper: 

https://github.com/raboof/nethogs/blob/3e0bba6966dbadf1cf08e1c5556e78d753fb9f5a/src/main.cpp#L211-L225

Removing this check makes things work. Is there a better way to check for the process' current capabilities?

**Comment by raboof** [comment]
Any recommendations on how to fix this are greatly appreciated, realistically I don't expect to find time to look into this myself.

**Comment by ncfavier** [comment]
The two ways I can see are:
1. remove the check altogether and let things fail later down the line. It seems like the first thing that fails without CAP_NET_RAW is [`dp_open_live`](https://github.com/raboof/nethogs/blob/06fdccb41931961894fb4093512cea95aa4517c1/src/main.cpp#L255) with "Error opening pcap handlers for all devices.", maybe that can be given a more informative error message. I don't know what CAP_NET_ADMIN is needed for.
2. Pull in libcap and check the current process' capabilities using [`cap_get_proc`](https://man7.org/linux/man-pages/man3/cap_get_proc.3.html).

I'm somewhat partial to the "don't check, handle failure" approach.

**Comment by raboof** [comment]
> I'm somewhat partial to the "don't check, handle failure" approach.

That makes sense to me - especially if we could give good feedback in the "handle failure" part. Would you be interested in providing a PR?

**Comment by ncfavier** [comment]
Done #215

**Comment by ncfavier** [comment]
Would you consider making a new release please? It's been almost exactly two years since the last one :smile:

**Comment by raboof** [comment]
Done!

**Comment by ncfavier** [comment]
Thanks!
