### ISSUE TITLE
Option to show process arguments

### ISSUE THREAD

**Issue by TheAmigo** [raboof/nethogs#23]
When there are multiple instances of a process running, it would be much more helpful to if nethogs could show the arguments to all processes.

**Comment by raboof** [comment]
Agreed! Perhaps we should add a `-c` flag like `top`

**Comment by raboof** [comment]
Hmm, we actually already show the arguments, right? For example I see `..sr/lib/chromium/chromium --show-component-extension-options --ignore-gpu-blacklist --disable-background-n`.

Related to #103 .

**Comment by TheAmigo** [comment]
On RHEL 7.1 running the nethogs 0.8.5 (built from source) I don't see arguments for any process.  Lots of "ssh", "/usr/bin/perl", and other commands, but no arguments for any of the.  Tried both "sudo nethogs" and running nethogs from a root shell... still no arguments.
![screenshot_2016-11-16_11-47-40](https://cloud.githubusercontent.com/assets/4148739/20358878/23808f40-abf3-11e6-9853-72ec6dfc262a.png)

**Comment by raboof** [comment]
Ah, it seems chromium does something 'special' there: if I look at `/proc/<pid>/cmdline`, usually for commands like `perl` the command is separated from the parameters with `\0` characters, but for chrome they're spaces. Odd.

**Comment by TheAmigo** [comment]
I don't have Chrome installed on this machine right now so I can't check... it's possibly an artifact of a wrapper script Chrome uses that ends up joining all its arguments with spaces between them.  Null bytes are the standard delimiter so that individual arguments can have space in them without being confused with being separate args.

**Comment by anomen-s** [comment]
I confirm, Chrome rewrites cmdline,
https://cs.chromium.org/chromium/src/content/common/set_process_title.cc

As for this issue, I almost finished implemetation, anomen-s/nethogs@d74711e9e9
