### ISSUE TITLE
[libnethogs.so.0.8.7] undefined symbol: pidsToWatch

### ISSUE THREAD

**Issue by Galicarnax** [raboof/nethogs#230]
After `nethogs` updated to `0.8.7` on Arch Linux, Python wrapper for `nethogs` library stopped working, saying
```
OSError: /usr/lib/libnethogs.so.0.8.7: undefined symbol: pidsToWatch
``` 
Looking into the sources, I can see that `pidsToWatch` is declared in `process.cpp` as `extern std::set<pid_t> pidsToWatch;`, but it is defined in `main.cpp`, which is not part of the library (if I understand correctly).

**Comment by sgtcortez** [comment]
I will take a look this week.

**Comment by NeilZhy** [comment]
I had the same problem and I think the `pidsToWatch` should put into `process.cpp`.

**Comment by guihkx** [comment]
Gentle ping.

**Comment by raboof** [comment]
(I don't have the bandwidth to work on nethogs myself right now, but a PR is definitely appreciated!)

**Comment by bphd** [comment]
> Gentle ping.

**Comment by sgtcortez** [comment]
Hi, I have made this [commit](https://github.com/sgtcortez/nethogs/commit/9745fee10e7ea51ba12a1da7b68c4e4a82b9a522) which might fix everything.

I have made `make` and `make libnethogs` 

And compiled successfully.

Do you have any other command to check if everything will work? For example, compile with python bindings. I havent worked with bindinds yet, so, I you could help me. 
I would be glad @Galicarnax

**Comment by DiedByDisgust** [comment]
> Hi, I have made this [commit](https://github.com/sgtcortez/nethogs/commit/9745fee10e7ea51ba12a1da7b68c4e4a82b9a522) which might fix everything.

tested, works for me. 👍

**Comment by Galicarnax** [comment]
Any reason this is still not pulled into the main repo? E.g., in Arch Linux, `nethogs` v.0.8.7.2 is still distributed with this bug.

**Comment by raboof** [comment]
tagged 0.8.8 if that helps
