### ISSUE TITLE
build error 0.8.7

### ISSUE THREAD

**Issue by NeilZhy** [raboof/nethogs#235]
I get the flowing error, when i run `make libnethogs`:
`g++  -Wall -Wextra -Wno-missing-field-initializers --std=c++0x -O3 -fPIC -fvisibility=hidden  -o obj/lib/release/connection.o -c connection.cpp
connection.cpp: In function ‘Connection* findConnectionWithMatchingSource(Packet*, short int)’:
connection.cpp:162:37: error: no matching function for call to ‘std::multiset<Connection*, ConnectionComparator>::lower_bound(Packet*)’
  162 |   auto it = connList->lower_bound(&p);`
The error is as goog ad other one:  [#225 ](https://github.com/raboof/nethogs/issues/225)

**Comment by NeilZhy** [comment]
I tried to push the fixed code, but I didn't have permission.

**Comment by raboof** [comment]
> I tried to push the fixed code, but I didn't have permission.

Thanks for looking into it! You can create a fork on GitHub, push to that fork, and then create a Pull Request to propose merging it into this repository

**Comment by NeilZhy** [comment]
> > I tried to push the fixed code, but I didn't have permission.
> 
> Thanks for looking into it! You can create a fork on GitHub, push to that fork, and then create a Pull Request to propose merging it into this repository

Thanks you! I have submitted the PR.
