### ISSUE TITLE
macos problem

### ISSUE THREAD

**Issue by koval01** [raboof/nethogs#243]
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/61350874/196170451-ac84e409-3005-4cd2-87db-fc004a1cec64.png">
Your utility does not work correctly on macOS

<img width="299" alt="image" src="https://user-images.githubusercontent.com/61350874/196170838-54b610fa-0209-452a-a22c-8f9cd87eda62.png">

**Comment by raboof** [comment]
Indeed nethogs is only useful on Linux, as the README says:

```
Since NetHogs heavily relies on /proc, most features are only available on Linux. NetHogs can be built on Mac OS X and FreeBSD, but it will only show connections, not processes.
```

That suggests it _should_ show connections on macos, but maybe that broke somehow - anyway there's many tools for showing connections, the unique thing of nethogs is the association with processes, so I don't think it makes sense to run nethogs on macos at this point in time. I'd be happy to consider a contribution adding it, but am not planning on working on this myself.
