### ISSUE TITLE
creating socket failed while establishing local IP - are you root?

### ISSUE THREAD

**Issue by Polochamps** [raboof/nethogs#25]
Ubuntu 16.04.

nethogs not working after updating kernel to 4.4.0-2

**Comment by raboof** [comment]
This has been fixed in version 0.8.1, but that hasn't made it into Debian yet (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811273), and thus not into Ubuntu.

**Comment by IamC8** [comment]
Its quite easy to create your own deb package.

sudo apt-get install build-essential automake autoconf libtool pkg-config libcurl4-openssl-dev intltool libxml2-dev libgtk2.0-dev libnotify-dev libglib2.0-dev libevent-dev checkinstall

wget https://github.com/raboof/nethogs/archive/v0.8.1.tar.gz

tar xvf v0.8.1.tar.gz

cd nethogs-0.8.1

sudo apt-get install ncurses-dev libpcap-dev

make

sudo checkinstall

enjoy...

**Comment by raboof** [comment]
The fixed version has also already made it into Debian Unstable (https://packages.debian.org/search?keywords=nethogs&searchon=names&suite=all&section=all), so AFAIK it should be slowly trickling down to testing and Ubuntu now...
