### ISSUE TITLE
[Question] License terms when using libnethogs dynamically linked

### ISSUE THREAD

**Issue by lleon95** [raboof/nethogs#274]
Hi all,

Thanks for sharing your project. Quite useful. I am developing a tool for measuring the energy consumption per process, and I might need to introduce the network as a variable in the mathematical model. I have concerns about using libnethogs inside of my code base. 

I plan to use the API from libnethogs and link dynamically. I saw that the entire code is under GPL-v2. However, this does not contemplate dynamic linking. Is there a plan to license the library under LGPL-v2?

My tool is licensed under LGPL, precisely.

I appreciate your help.

Leon

**Comment by raboof** [comment]
Thanks for your interest! Unfortunately I've taken various contributions to nethogs over the years, and those were all under the GPL, so I can't relicense the project.

**Comment by lleon95** [comment]
I was looking at the [FSF FAQ](https://www.gnu.org/licenses/gpl-faq.html#compat-matrix-footnote-7):

![image](https://github.com/raboof/nethogs/assets/7350785/5f2fe7a3-a79f-4a99-811b-66aa9e1d8cac)

So, it seems I should be able to do as it is right now.

**Comment by raboof** [comment]
Great! I'll close this issue then :)
