### ISSUE TITLE
mark 0.8.8 as latest release?

### ISSUE THREAD

**Issue by chenrui333** [raboof/nethogs#280]
👋 looks like a github release notes is missing for the 0.8.8 release, raise this issue for some awareness. Thanks!

![image](https://github.com/user-attachments/assets/df26f2d4-f588-4962-8617-f91708215d39)

relates to https://github.com/Homebrew/homebrew-core/pull/193047

**Comment by raboof** [comment]
done

**Comment by chenrui333** [comment]
Thanks @raboof!
