### ISSUE TITLE
Add commandline option to disable PROCESSTIMEOUT and/or CONNTIMEOUT

### ISSUE THREAD

**Issue by cgx027** [raboof/nethogs#39]
Hello,

We spotted nethogs and were hoping to use it to help drive out some benchmarks on the per-process network usage in our tooling (https://github.com/rackhd/), which is set up as a distributed system.

I am using nethogs in tracemode and monitor my traffic on a specific port (I would love to do per-process monitor but per #31, I am not yet able to do that). I would store the output, parse it, and plot it into a charter for later analysis. I would like to have one log item each second so that not to leave a time hole in the log file. 

The problem is that, nethogs will stop to print any log files, after the traffic has been silent for 50 seconds. Resuming traffic after that will not make it print any further output. 

Dug a little bit into the source, I think this is because CONNTIMEOUT is set to 50. I guess there is a reason to set a timeout, but maybe we can provide command line option to disable the timeout, so that I can get constant logs, even when the traffic is not constant. 

How do you think?

**Comment by raboof** [comment]
Thanks for spotting this, this sounds like a bug.

**Comment by raboof** [comment]
`CONNTIMEOUT` is already ignored when you choose one of the cumulative view modes (`-v 1`/2/3). Are you running nethogs showing kbps or a cumulative view?

**Comment by raboof** [comment]
@cgx027 if you were indeed using another mode than kbps, #56 might solve your problem - could you verify?
