### ISSUE TITLE
High CPU usage on low-end machines

### ISSUE THREAD

**Issue by mb-gh** [raboof/nethogs#42]
I have a low-end laptop with limited CPU and nethogs causes a constant 4 to 5 % CPU usage.
I found that this is caused by the the very short sleep time in the main loop
```
if (!packets_read)
{
     usleep(100);
}
```
I did some attempts and noticed that increasing the sleep time to few milliseconds fixes the issue with no  side effects.

**Comment by raboof** [comment]
Indeed reducing CPU would be nice.

It is hard to tell, though, how long we can safely sleep: the problem is that when measuring short-lived connections, if the packets arrive and then the connection is closed within the 100ns that we're sleeping, we won't know what connection (and thus what process) to associate this process with.

There are some opportunities in improving this by changing the way we deal with libpcap and concurrency. Some work has been done in #5 but I'm not sure that approach will work.

In the mean time I'd be OK with making the sleep time configurable and upping the default to something like 3000?

**Comment by mb-gh** [comment]
My understanding is that libpcap does buffer the packets until the next 'dispatch' so I think there is no way to miss packets... this needs to be confirmed, but if it's the case, there is no problem with the sleep... and during something like 50 milliseconds of buffering, the buffer size wont exceed few megs even with a very fast connection.

Another way to use libpcap is to use the 'blocking' poll instead of the non-blocking dispatch... but this means multithreading in the case of multiple network interfaces... and it means synchronisation between the different threads to access to common data structures... which would be very complicated to implemented with the current design...

My suggestion is to confirm my assumption regarding the pcap_dispatch if it's confirmed it does not miss packets.. then we can increase the sleep time and have a lot better performance.

**Comment by mb-gh** [comment]
I am testing this right now...

**Comment by mb-gh** [comment]
OK My bad, I tested with a very long sleep in the code and indeed it does miss connection...

**Comment by mb-gh** [comment]
So, I actually looked up this issue and there is 2 solutions:
- 1 - use pcap_get_selectable_fd() call to get a file descriptor supporting select() 
- 2 - use pcap_loop() instead of dispatch.
The problem with solution 1 is that it does not work on all possible network devices.
The problem with solution 2 is that it will induce use of multi threading and mutexes... and that my make thing a little more complex.

**Comment by mb-gh** [comment]
I think an ideal solution is to have a thread doing a pcap_loop() on each network device and then a global mutex lock on the callback so that only one thread call change the structures at a time...
Everything beyond that should work as normal. 
I am not sure if you are confortable with this attempt though... what do you think?

**Comment by mb-gh** [comment]
You may also want to have a look at this: https://sourceforge.net/p/libpcap/bugs/166/

**Comment by mb-gh** [comment]
And this: https://github.com/the-tcpdump-group/libpcap/issues/169

**Comment by raboof** [comment]
I'm a bit afraid to introduce multithreading to nethogs, if we need that we might be better off rewriting nethogs in a language that makes it easier to get that right :).

pcap_get_selectable_fd sounds great. Did you find anything suggesting that doesn't work on recent versions of OSX?

**Comment by mb-gh** [comment]
No, I think it's more about the old versions. I have attempted to use pcap_get_selectable_fd and it worked on my laptop. I will do a PR so you can have a look.

**Comment by raboof** [comment]
Right - for Linux I think it makes sense to support some older versions, but for OSX I'd say we can make some assumptions on how recent those are likely to be :). Would be great if we can streamline this!

**Comment by mb-gh** [comment]
I am trying to showcase this to you in less than an hour :)

**Comment by mb-gh** [comment]
PR ready https://github.com/raboof/nethogs/pull/43
