### ISSUE TITLE
Consider using clang-format to clean up style inconsistencies and establish style

### ISSUE THREAD

**Issue by nibroc** [raboof/nethogs#44]
As discussed in passing [here](https://github.com/raboof/nethogs/pull/40#issuecomment-192973818) and the few comments after it, there seems to an interest in getting back to and maintaining a consistent style. I think clang-format would be the easiest way to do this since it would allow:

1. Determine and codify a style guidelines (i.e. use one of the [existing styles](http://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options) or make a custom one).
2. Make a `make` task to reformat all of the source code.
3. Do a one-time mass formatting to bring all of the code into the new style (e.g. a normal `make format` that would just affect a ton of stuff)
4. In the future, require contributors to `make format` before pull requesting.

If you're interested in this approach, I can easily put together a config for clang-format and a `make` task. I just need to know what the desired style is.

**Comment by mb-gh** [comment]
I think it's a great idea.
But I would recommend waiting for the pending PR to me merged before applying the `make` command.
Let's see what @raboof think about it.

**Comment by raboof** [comment]
Great idea! Let's pick a standard.

* I like to allow 'else' after 'return' (like in 'if (foo) { return bar; } else { return baz; }'), which is not allowed by LLVM
* I like naming functions 'lowerCamelCase', so that disqualifies Google/Chromium/Mozilla.
* webkit promotes using end-of-line comments while I prefer putting them above.

Oops, looks like we have no standards left to choose from :).

The 'general feel' of LLVM seems most solid, perhaps we should select that one but not enforce the 'else after return' rule? What do you think?

I agree with @mb-gh we should probably wait until we have less PR's open before we apply the rules to the whole codebase, but a PR adding the Make target would already be interesting.

**Comment by nibroc** [comment]
I could be wrong on this, but I think there's a difference between the style guide for those projects and the clang-format settings. I don't think clang-format is even capable of enforcing the first item, for example. I guess this means that we can't *entirely* rely on clang-format. There will still need to be some kind of style guide to maintain some of the finer consistency (I don't think clang-format can enforce function naming scheme either, for example, and even if it can, I don't know if it will change them).

It looks trivial to export the settings for one of the built in standards and then tweak them, so I'll make an attempt to come up with something LLVM based, and I'll try to find some good snippets out of the nethogs code base to run through clang-format. Once I have that, I'll put the settings and formatted snippets up here, and we can tweak the rules from there.

@mb-gh I agree. It looks like your PR is going to be a rather huge and merge-conflict-tastic commit, so I shall certainly wait :).

**Comment by raboof** [comment]
Right, even when the tool can't validate/fix everything, I think it makes sense to be able to point contributors to a standard set of rules, and LLVM (without the 'else after return' rule) seems reasonable.

**Comment by raboof** [comment]
See #52 , WDYT?

**Comment by nibroc** [comment]
Looks good, @raboof! I wish clang-format could do a bit more style fixing than it did (adding in missing `{}` for example), but such is life I suppose. 

I'm also starting to wonder if maybe nethogs needs a style guide of its own, or to perhaps call out which specific parts of LLVM you want to adhere to. For example, LLVM's style guide dictates that exceptions cannot be used. Is that the plan moving forward (I certainly hope not personally), or an accidental inheritance of LLVM? I suspect there's other components of LLVM that might be a bit undesirable as well.

**Comment by raboof** [comment]
Agreed on both points! We can list exceptions/addenda to the LLVM style in the README
