### ISSUE TITLE
Create a "latest" release

### ISSUE THREAD

**Issue by edouard-lopez** [raboof/nethogs#55]
Could you **create a release** so we can have a "latest" version available?

I reckon existing releases are tags automagically converted as releases. 

> Github now provides a "Latest release" button on the release page of a project, after you have created your first release.

source: http://stackoverflow.com/a/22507358/802365

**Comment by raboof** [comment]
I wonder if that only works when I release from the GitHub UI, or also when I tag a release myself. Let's release 0.8.2 some time soon and see :)

**Comment by raboof** [comment]
Out of curiosity: is there a particular reason you're interested in seeing a 'latest' release?

**Comment by edouard-lopez** [comment]
It's helpful when you want to create install script or answer on [stackoverflow](http://askubuntu.com/a/729560/22343).

**Comment by raboof** [comment]
We've been publishing releases for a while now :)
