### ISSUE TITLE
nethogs does not count throughput correctly

### ISSUE THREAD

**Issue by pyrovski** [raboof/nethogs#6]
Tested with iperf between two hosts, nethogs reports 2 MBps while iperf reports 10+ MBps.

**Comment by raboof** [comment]
Interesting! I would appreciate a tcpdump of such a test run.

**Comment by mrbarletta** [comment]
I tested 2 ubuntu laptops with iperf 2.0.5 on a AC network.

Didn't see any substantial difference.  

Note that Iperf reports in Mbits and nethogs in KB.

**Comment by raboof** [comment]
Closing this issue until it can be reproduced
