### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by raboof** [raboof/nethogs#62]

**Comment by pavan02** [comment]
Is this still open ? I can see #10 open as well..

If not its implemented yet, what does below the callback functions do?
 
https://github.com/raboof/nethogs/blob/master/src/main.cpp#L241

dp_addcb(newhandle, dp_packet_ip, process_ip);
dp_addcb(newhandle, dp_packet_ip6, process_ip6);
dp_addcb(newhandle, dp_packet_tcp, process_tcp);
dp_addcb(newhandle, dp_packet_udp, process_udp);

**Comment by pavan02** [comment]
s this still open ? I can see #10 open as well..

If not its implemented yet, what does the below callback functions do?

https://github.com/raboof/nethogs/blob/master/src/main.cpp#L241

dp_addcb(newhandle, dp_packet_ip, process_ip);
dp_addcb(newhandle, dp_packet_ip6, process_ip6);
dp_addcb(newhandle, dp_packet_tcp, process_tcp);
dp_addcb(newhandle, dp_packet_udp, process_udp);

**Comment by pavan02** [comment]
Is this still open ? I can see #10 open as well..

If not its implemented yet, what does the below callback functions do?

https://github.com/raboof/nethogs/blob/master/src/main.cpp#L241

dp_addcb(newhandle, dp_packet_ip, process_ip);
dp_addcb(newhandle, dp_packet_ip6, process_ip6);
dp_addcb(newhandle, dp_packet_tcp, process_tcp);
dp_addcb(newhandle, dp_packet_udp, process_udp);

**Comment by raboof** [comment]
Nethogs used to capture UDP traffic and show all UDP traffic as 'unknown UDP'. I think I stopped showing that because it wasn't very useful anyway, and I'm not sure I could reliably determine whether the packets were incoming or outgoing. Actually reliably associating them with processes I'm not sure is possible.

So yes, this ticket is open, but I'm not sure if there's any useful information we can reasonably show for UDP traffic. What do you think?

**Comment by pavan02** [comment]
Hmm...I still trying to figure out how nethogs work with TCP....any pointers would be of great help.
What do mean by reliably ? What's the difficulty/tricky part with UDP traffic?

Total data usage like in this ticket #109 could be useful...

BTW what about #10 ?  Is it already implemented ?

**Comment by raboof** [comment]
Wrt #10, I'm not entirely sure
