### ISSUE TITLE
Cannot make install

### ISSUE THREAD

**Issue by kenahrens** [raboof/nethogs#67]
I'm running ubuntu 14.04. I installed the pre-requisites and ran make successfully (can run nethogs from the src directory). But when I run sudo make install I get an error. Here is my output:

```
kahrens@lrevo:~/dev/nethogs$ sudo make install
make -C src -f MakeApp.mk install
make[1]: Entering directory `/home/kahrens/dev/nethogs/src'
make[1]: *** No rule to make target `nethogs.8', needed by `install'.  Stop.
make[1]: Leaving directory `/home/kahrens/dev/nethogs/src'
make: *** [install] Error 2
```

I looked inside MakeApp.mk and it does reference nethogs.8. Where does that get built?

**Comment by ReallyLuvMDDrivers** [comment]
You beat me to it @kenahrens. Only difference is I'm using Ubuntu Server 14.04. The only thing I noticed about nethogs.8 is that it seems to be the man page reference. Nethogs.8 is in the doc folder but I don't see it being ref'ed in the mk or any other file.

**Comment by raboof** [comment]
Good catch, thanks! I shuffled the build system a bit recently and it seems this slipped through the cracks.

Could you give it another try? Should be OK now again!

**Comment by raboof** [comment]
(nethogs.8 it was referenced from `src/MakeApp.mk`, I moved that to `doc/Makefile`)

**Comment by kenahrens** [comment]
@raboof - thanks, that worked for me on ubuntu 14.04. Cheers!

**Comment by ReallyLuvMDDrivers** [comment]
I concur. No errors. Ty vm....
