### ISSUE TITLE
Running nethogs without root

### ISSUE THREAD

**Issue by matan129** [raboof/nethogs#86]
I'm using [hogwatch](https://github.com/akshayKMR/hogwatch), and I don't want to run it with root permissions. When I run it I get the message 

> to run nethogs without being root you need to enable capabilities on the program (cap_net_admin, cap_net_raw), see the documentation for details.

I couldn't find another reference to this anywhere (are there _any_ docs?), can you clarify how to do it?

**Comment by aib** [comment]
See setcap(8), or https://www.kernel.org/pub/linux/libs/security/linux-privs/kernel-2.2/capfaq-0.2.txt.

As for how to do it:
># setcap "cap_net_admin,cap_net_raw=ep" nethogs

**Comment by raboof** [comment]
Would be nice to include this more clearly in the README, let's keep this issue open until we've 'fixed' that!

**Comment by kant111** [comment]
I just installed nethogs using `apt-get` and it still requires root access

**Comment by raboof** [comment]
That's correct, by default nethogs is not installed with those capabilities opened up for all users.

Starting nethogs as non-root user should give you an error like:
```
$ /usr/sbin/nethogs -d 1
To run nethogs without being root you need to enable capabilities on the program (cap_net_admin, cap_net_raw), see the documentation for details.
$
```
Then after adding the capabilities:
```
$ sudo setcap "cap_net_admin,cap_net_raw=ep" /usr/sbin/nethogs
```

.. now you should be able to run nethogs even from a non-root account. Let me know if you run into any problems!

**Comment by reggler** [comment]
Hi, I've executed this but got the following:
```
$ nethogs
You need to be root to run NetHogs!
$ sudo setcap "cap_net_admin,cap_net_raw=ep" /usr/sbin/nethogs
$ nethogs
You need to be root to run NetHogs!
```
This is on Ubuntu 16.04 and nethogs got installedf with apt-get

How do I fix this?

**Comment by raboof** [comment]
Interesting. Can you post the output of "which nethogs"?

**Comment by reggler** [comment]
/usr/sbin/nethogs

**Comment by shirishag75** [comment]
It works at my end - 

Before - 

```
[$] nethogs --version                                                                                                              
zsh: command not found: nethogs
Command 'nethogs' is available in '/usr/sbin/nethogs'                                                                                           
The command could not be located because '/usr/sbin' is not included in the PATH environment variable.
This is most likely caused by the lack of administrative priviledges associated with your user account.
nethogs: command not found

[$] apt-cache policy nethogs                                                                                                       
nethogs:
  Installed: 0.8.5-2
  Candidate: 0.8.5-2
  Version table:
 *** 0.8.5-2 600
        600 http://httpredir.debian.org/debian buster/main amd64 Packages
          1 http://httpredir.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status

```

After doing the needful - 

```
[$]  sudo setcap "cap_net_admin,cap_net_raw=ep" /usr/sbin/nethogs                                                                  
[sudo] password for user: 

[$] /usr/sbin/nethogs -d 1                                                                                                        
Ethernet link detected
                      Waiting for first packet to arrive (see sourceforge.net bug 1019381)

[$] /usr/sbin/nethogs --help                                                                                                      
/usr/sbin/nethogs: invalid option -- '-'
usage: nethogs [-V] [-h] [-b] [-d seconds] [-v mode] [-c count] [-t] [-p] [-s] [device [device [device ...]]]
		-V : prints version.
		-h : prints this help.
		-b : bughunt mode - implies tracemode.
		-d : delay for update refresh rate in seconds. default is 1.
		-v : view mode (0 = KB/s, 1 = total KB, 2 = total B, 3 = total MB). default is 0.
		-c : number of updates. default is 0 (unlimited).
		-t : tracemode.
		-p : sniff in promiscious mode (not recommended).
		-s : sort output by sent column.
   -a : monitor all devices, even loopback/stopped ones.
		device : device(s) to monitor. default is all interfaces up and running excluding loopback

```

This could be further simplified by making nethogs alias to /usr/sbin/nethogs either in bash or whatever terminal you use.

**Comment by Omnikron13** [comment]
Should this not be explained in the man page? When I saw that message saying to 'see the documentation for details' that's where I assumed it would be detailed, personally. (I don't think anyone is even likely to have the readme if they install from their distros repos, let alone think to look there?)

**Comment by raboof** [comment]
@Omnikron13 sounds good! Would you like to PR?

**Comment by Omnikron13** [comment]
Sure, I'll put something together when I've got a little time.
