### ISSUE TITLE
Tarballs aren't signed

### ISSUE THREAD

**Issue by kretcheu** [raboof/nethogs#89]
Hi,

I'm the new mainatiner of Nethogs Debian package and I have a suggestion:
Please assign tarballs files by gpg signature of the author.

**Comment by raboof** [comment]
@kretcheu instead of rolling a tarball, I've created a signed tag (https://github.com/raboof/nethogs/releases/tag/v0.8.2) - does that work for you?

**Comment by kretcheu** [comment]
Hi Raboof,

thanks for your work.

In Debian usually upstream's tarballs are signed because Debian structure can verify authenticity of upstream sources, that we respect very much.

In Debian wiki you can read more about it: https://wiki.debian.org/UpstreamGuide

If you have any doubts, let me know.

Thanks.

**Comment by raboof** [comment]
I've uploaded a 'detached' signature to github along with the github-generated tarball as described in the 'alternative' workflow at https://wiki.debian.org/Creating%20signed%20GitHub%20releases .

Thanks for the heads-up!
