### ISSUE TITLE
'creating socket failed while establishing local IP' on kernels from 4.3.0 

### ISSUE THREAD

**Issue by raboof** [raboof/nethogs#9]

**Comment by PeterPablo** [comment]
Back-reference: https://github.com/raspberrypi/firmware/issues/521

**Comment by raboof** [comment]
Should be fixed in 0.8.1 indeed! Let me know if you run into any further trouble

**Comment by edouard-lopez** [comment]
For reference, I got this issue on Kubuntu `15.10` and `0.8.0`

### Kernel
```
$ uname -a
Linux xyz 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### Release
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

### Version

```
$ nethogs -V
version 0.8.0
```

**Comment by edouard-lopez** [comment]
As it's not available in repo nor PPA you **need to build it** (it is really **easy and quickly done**).


### Fetch and extract

    wget -c https://github.com/raboof/nethogs/archive/v0.8.1.tar.gz
    tar xf v0.8.1.tar.gz 
    cd ./nethogs-0.8.1/

### Install dependencies and build

    sudo apt-get install libncurses5-dev libpcap-dev
    make && sudo make install 

### Check and run

    nethogs -V
    sudo nethogs

Also in [Nethogs → creating socket failed while establishing local IP - are you root?](http://askubuntu.com/a/729560/22343)
  [1]: https://github.com/raboof/nethogs/issues/

**Comment by edouard-lopez** [comment]
@raboof After some wonder I went across the [`checkinstall` tool](http://checkinstall.izto.org/) that relly simplify package creation for `RedHat`-based and `Debian`-based distros. 

It installs and creates a package for your distro your local dir, so you can easily install/uninstall/distribute(?) the tool:

```
make && sudo -k checkinstall \
    --pkgsource="https://github.com/raboof/nethogs/" \
    --pkglicense="GPL2" \
    --deldesc=no \
    --nodoc \
    --maintainer="$USER\\<$USER@akema.fr\\>" \
    --pkgarch=$(dpkg \
    --print-architecture) \
    --pkgversion="0.8.1" \
    --pkgrelease="SNAPSHOT" \
    --pkgname=nethogs \
    --requires="libc6 \(\>= 2.4\),libgcc1 \(\>= 1:4.1.1\),libncurses5 \(\>= 5.5-5~\),libpcap0.8 \(\>= 0.9.8\),libstdc++6 \(\>= 4.1.1\),libtinfo5" \
    make install
`
Maybe you can hook it with github or a CI integration tool.
