### ISSUE TITLE
Missing LIBVERSION information

### ISSUE THREAD

**Issue by keenerd** [raboof/nethogs#92]
The makefile installs an oddly (un)versioned library to `/usr/lib/libnethogs.so...` and I suspect there should be numbers between the dots.  Those numbers pull from `LIBVERSION LIBSUBVERSION LIBMINORVERSION` which are not set in the makefile.  As a packaging workaround I'm setting them all to zero, for `libnethogs.so.0.0.0`

**Comment by raboof** [comment]
Indeed that's not great!

Are you installing from github or from a source tarball? If from a source tarball, can I assume it's in the "nethogs-VERSION" directory?

**Comment by keenerd** [comment]
Yes, it was a source tarball  The 0.8.2 release.

**Comment by raboof** [comment]
I've tried a new way of tagging a release with a version and did version 0.8.3 with that.

That should fix this, agreed?
