### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by NoSuck** [raboof/nethogs#96]
I use nethogs 0.8.5 on Linux 4.6.4-1-ARCH and have noticed that when selecting the cumulative MB display by cycling with "m," hours later I can return to the computer to find nethogs crippling my system with its memory usage... or was it CPU?  I will confirm.

Has anyone else experienced this?

Edit:  It is CPU.

**Comment by raboof** [comment]
Hi, thanks for your message! So far indeed nethogs has not really been optimized for the long-running use case.

Presumably there is some leak that makes some data structure grow unbounded, leading to CPU usage when traversing that data structure.

I'd welcome help in pinpointing what structure is causing this!

**Comment by webzorg** [comment]
I left it version 0.8.5-2 running for a week on debian and memory usage was at 4gb

**Comment by wodencafe** [comment]
I also have this bug, using 0.8.5-2, after a few days the memory usage was >1GB, and CPU usage was very high too.

**Comment by raboof** [comment]
Likely fixed by #203 , feel free to open a new issue when you encounter a leak after this change
